[workspace]
resolver = "3"
members = ["colls"]

[workspace.package]
license = "MIT-0"
readme = "README.md"
repository = "https://github.com/Viterkim/colls"
version = "0.0.1"
edition = "2024"
rust-version = "1.89"
publish = true

[workspace.dependencies]
er = { version = "0.5", default-features = false, features = ["macros"] }
hashbrown = { version = "0.17", default-features = false, features = ["default-hasher"] }
parking_lot = "0.12"

[workspace.lints.rust]
unsafe_code = "deny"
